name: Bun.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
          bun-version: 1.2.20

    - run: bun install
    - run: bun run ci
